---

- name: Build and Upload Admin Frontend to S3 Bucket
  hosts: localhost

  vars:
    bucket_name: ucm-{{ ENV }}-ui-admin
    bucket_url: '{{ bucket_name }}.s3-website-us-east-1.amazonaws.com'
    aws_region: us-east-1

  tasks:
    - name: Create S3 bucket if non-existent
      amazon.aws.aws_s3:
        bucket: '{{ bucket_name }}'
        region: '{{ aws_region }}'
        mode: create
        permission: public-read

    - name: Configure S3 bucket to static website
      s3_website:
        name: '{{ bucket_name }}'
        region: '{{ aws_region }}'
        suffix: index.html
        state: present

    - name: Upload admin frontend to S3 bucket
      community.aws.s3_sync:
        bucket: '{{ bucket_name }}'
        region: '{{ aws_region }}'
        file_root: ../dist/admin-ui
        permission: public-read
        include: "*"

    - name: Create a basic CloudFront distribution
      community.aws.cloudfront_distribution:
        state: present
        caller_reference: 'admin-{{ ENV }}-cashmoney'
        default_origin_domain_name: '{{ bucket_url }}'
        aliases: ['admin-{{ ENV }}.utopiancashmoney.de']
        price_class: PriceClass_100
        viewer_certificate:
          acm_certificate_arn: arn:aws:acm:us-east-1:202447729588:certificate/24295935-8af6-4c69-956c-37d41dec074b
          ssl_support_method: sni-only
        tags:
          Name: '{{ ENV }} Admin UI distribution'
          Project: 'CashMoney Banking'
          Priority: '1'
        origins:
          - id: 'admin frontend origin'
            domain_name: 
            origin_path: /admin
      register: dist
      
    - name: Create Route53 record pointing to CloudFront distribution
      community.aws.route53:
        state: present
        zone: utopiancashmoney.de
        record: 'admin-{{ ENV }}.utopiancashmoney.de'
        type: CNAME
        ttl: 60
        value: '{{ dist.domain_name }}'
